#!/bin/bash

BASEDIR=$(dirname $(readlink -f ${0}))
source "${BASEDIR}/common.sh"
source "${BASEDIR}/gitlab.sh"
source "${BASEDIR}/rt.sh"
source "${BASEDIR}/openssl.sh"
source "${BASEDIR}/k8s.sh"
source "${BASEDIR}/clusters.sh"
source "${BASEDIR}/apps.sh"

GOCLI_DIR=~/.gocli

if [[ -f "${BASEDIR}/.env" ]]; then
    source "${BASEDIR}/.env"
fi

if [[ ! -d "${GOCLI_DIR}/clusters" ]]; then
    mkdir -p "${GOCLI_DIR}/clusters"
    chmod 0700 "${GOCLI_DIR}/clusters"
fi

CLUSTER_DEFAULT_BRANCH=template

case "$1" in
    clusters)
        clusters
        ;;
    apps)
        apps
        ;;
    *)
        echo "Usage: $0 clusters|apps"
        ;;
esac
